name: locationd
version: 4.0.0
confinement: strict
summary: Location service mediates access to positioning providers.
description: |
  Location service mediates access to positioning providers.

  Please find the source for this snap at https://code.launchpad.net/location-service

apps:
  run:
    daemon: simple
    command: bin/locationd run --bus=system
    slots: [service-control, service-observe]
    plugs: [ubx, network, network-manager]
  list-providers:
    command: bin/locationd list    
  status:
    command: bin/locationd status --bus=system
    plugs: [client-observe]
  monitor:
    command: bin/locationd monitor --bus=system
    plugs: [client-control, client-observe]
  provide:
    command: bin/locationd provider --bus=system
    plugs: [client-control, network]
  set:
    command: bin/locationd set
  test:
    command: bin/locationd test
    plugs: [ubx, network]

slots:
    service-observe:
        interface: location-observe
    service-control:
        interface: location-control
plugs:
    client-observe:
        interface: location-observe
    client-control:
        interface: location-control
    ubx:
        interface: serial-port

parts:
  hooks:
    plugin: dump
    source: prebuilt
  location-service:
    plugin: cmake
    configflags:
      - -DCMAKE_VERBOSE_MAKEFILE=ON
      - -DSNAPPY_UBUNTU_CORE=yes
      - -DUBUNTU_LOCATION_SERVICE_VERSION_MAJOR=4
    source: .
    build-packages:
      - cmake
      - cmake-extras
      - curl
      - doxygen
      - gcc
      - geoclue-ubuntu-geoip
      - gettext
      - google-mock
      - graphviz
      - g++
      - libapparmor-dev
      - libboost-filesystem-dev
      - libboost-locale-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - libc6-dev
      - libdbus-1-dev
      - libdbus-cpp-dev
      - libglib2.0-dev
      - libgflags-dev
      - libgoogle-glog-dev
      - libgtest-dev
      - libiw-dev
      - libjson-c-dev
      - libnet-cpp-dev
      - libprocess-cpp-dev
      - libtrust-store-dev
      - libproperties-cpp-dev
      - trust-store-bin
    stage-packages:
      - geoclue-ubuntu-geoip
    filesets:
      licenses:
        - usr/share/doc/*/*copyright*
    snap:
      - bin/locationd
      - etc/dbus-1/system.d
      - etc/gps.conf
      - lib/
      - lib/libubuntu-location-service*
      - share/ubuntu-location-service
      - usr/lib/
      - $licenses
